/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\public\models\plane\aeroplane.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
const HELIX_SPEED = 15;

export function Aeroplane(props) {
  const group = useRef()
  
  const { nodes, materials, animations } = useGLTF('./models/plane/aeroplane.glb')
  const { actions } = useAnimations(animations, group)
  const helix = useRef();
  useFrame((_state, delta) => {
    helix.current.rotation.y += delta * HELIX_SPEED;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="1fa73c0e0a4d4a019c2bd0b0de7678b6fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="supermarinespitfire" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object001" position={[-34.66, -38.21, 124.87]} rotation={[-Math.PI, 0.5, -Math.PI]}>
                    <group name="Object001001">
                      <mesh ref={helix} name="Object001_SupermarineSpitfire_0" geometry={nodes.Object001_SupermarineSpitfire_0.geometry} material={materials.SupermarineSpitfire_0} />
                    </group>
                  </group>
                  <group name="supermarinespitfire001" position={[-34.66, -38.21, 124.87]}>
                    <mesh  name="supermarinespitfire_SupermarineSpitfire_0" geometry={nodes.supermarinespitfire_SupermarineSpitfire_0.geometry} material={materials.SupermarineSpitfire} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/plane/aeroplane.glb')
